version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: iceverino/feature-0.1
    ports:
      - "5003:5000"
    env_file:
      - .env
    volumes:
      - /app  # cuidado com isso no deploy!
    environment:
      - FLASK_APP=wsgi:app
    command: flask run --host=0.0.0.0
